language: cpp 
sudo: required
dist: xenial 
os:
  - linux
install: true
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
before_install:
  - apt-get update && apt-get install -y build-essential cmake git zlib1g zlib1g-dev libssl-dev libcurl3 libcurl4-openssl-dev
  - echo $LANG
  - echo $LC_ALL
script:
  - 'make ${JOB}'
env:
  matrix:
    - JOB=deps
    - JOB=libnss_iam
    - JOB=pam
    - JOB=iam
    - JOB=test
jobs:
  fast_finish: true
